name: CI

on:
  workflow_dispatch:
    branches: [ master ]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [Win32, x64]
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Sandboxie
        run: msbuild /t:build Sandboxie\Sandbox.sln /p:Configuration="SbieRelease" /p:Platform=${{ matrix.platform }}

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.1'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
        
#      - name: Build Sandboxie-Plus
#        run: msbuild /t:build SandboxiePlus\SandboxiePlus.sln /p:Configuration="Release" /p:Platform=${{ matrix.platform }}
        
      - name: Upload Sandboxie
        uses: actions/upload-artifact@v2
        with:
          name: Sandboxie (${{ matrix.platform }})
          path: |
            Sandboxie/Bin/${{ matrix.platform }}/SbieRelease
            !**/*.pdb
            !**/*.ipdb
            !**/*.exp
            !**/*.ilk
            !**/*.iobj
            !**/*.lib
            !**/*.cer
            Sandboxie/Bin/${{ matrix.platform }}/SbieRelease/SbieDrv.pdb
