name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Build Driver
        run: msbuild /t:build Sandboxdrv.sln /p:Configuration="SbieRelease" /p:Platform="x64"
